import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { z } from "zod";
import type { CommandRunner, Config, Finding, RunState } from "./types";
import { AutopilotError } from "./errors";
import { StateStore } from "./state-store";
import { verify } from "./verification";
import { monitorCi } from "./github";
import { mergeGate } from "./policy";
import { remediationPrompt, reviewPrompt, unresolvedObjectiveFindings } from "./prompts";

type RunOptions = { cwd?: string; logFile?: string; timeoutMs?: number };
type ReviewResult = {
  reviewedCommit: string;
  verdict: "APPROVED" | "CHANGES_REQUIRED";
  findings: Finding[];
};

async function success(
  runner: CommandRunner,
  command: string[],
  code: string,
  options?: RunOptions,
) {
  const result = await runner.run(command, options);
  if (result.exitCode !== 0)
    throw new AutopilotError(result.stderr || `${command[0]} failed`, code);
  return result.stdout.trim();
}

function changedPaths(status: string) {
  return status
    .split("\n")
    .filter(Boolean)
    .map((line) => ({ code: line.slice(0, 2), path: line.slice(3).split(" -> ").at(-1)! }));
}

function agentOptions(root: string, state: RunState, config: Config, name: string, cwd = root) {
  return {
    cwd,
    timeoutMs: config.agentTimeoutSeconds * 1000,
    logFile: resolve(root, `.autopilot/logs/${state.runId}/${name}.log`),
  };
}

export async function assertRecordedBranch(runner: CommandRunner, state: RunState) {
  if (state.dryRun)
    throw new AutopilotError("Dry-run state cannot mutate the repository", "DRY_RUN_MUTATION");
  const current = await success(runner, ["git", "branch", "--show-current"], "GIT_BRANCH_FAILED");
  if (!state.branch || current !== state.branch)
    throw new AutopilotError(
      `Recorded branch ${state.branch ?? "<none>"} is not checked out`,
      "BRANCH_MISMATCH",
    );
}

export async function enforceChangeSafety(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
) {
  const statusResult = await runner.run(["git", "status", "--porcelain", "--untracked-files=all"]);
  if (statusResult.exitCode !== 0)
    throw new AutopilotError(statusResult.stderr || "git status failed", "DIFF_READ_FAILED");
  const status = statusResult.stdout;
  const changed = changedPaths(status);
  const protectedChange = changed.find(({ path }) =>
    config.protectedPaths.some(
      (protectedPath) => path === protectedPath || path.startsWith(`${protectedPath}/`),
    ),
  );
  if (protectedChange) {
    state.approvalGates.push(`protected path changed: ${protectedChange.path}`);
    throw new AutopilotError(`Protected path changed: ${protectedChange.path}`, "PROTECTED_PATH");
  }
  const migrations = changed.filter(({ path }) =>
    /^prisma\/migrations\/.+\/migration\.sql$/.test(path),
  );
  let destructive = migrations.some(({ code }) => code.includes("D"));
  for (const migration of migrations) {
    if (migration.code.includes("D")) continue;
    try {
      const sql = await readFile(resolve(root, migration.path), "utf8");
      if (/\b(DROP\s+(TABLE|COLUMN|TYPE)|TRUNCATE|DELETE\s+FROM)\b/i.test(sql)) destructive = true;
    } catch {
      destructive = true;
    }
  }
  if (destructive) {
    state.approvalGates.push("destructive schema migration requires human approval");
    throw new AutopilotError("Destructive migration detected", "APPROVAL_REQUIRED");
  }
}

export async function advanceImplemented(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
) {
  const store = new StateStore(root);
  await assertRecordedBranch(runner, state);
  state.phase = "VERIFYING";
  await store.save(state);
  state.verification = await verify(root, config, runner, state.runId);
  if (state.verification.some((value) => value.status === "FAILED")) {
    state.phase = "FAILED";
    state.failure = "Local verification failed";
    await store.save(state);
    return state;
  }
  state.phase = "VERIFIED";
  await store.save(state);
  await enforceChangeSafety(root, config, runner, state);
  await success(runner, ["git", "add", "-A"], "STAGE_FAILED");
  await success(
    runner,
    ["git", "commit", "-m", `feat: ${state.milestone!.title.toLowerCase()}`],
    "COMMIT_FAILED",
  );
  state.commit = await success(runner, ["git", "rev-parse", "HEAD"], "COMMIT_READ_FAILED");
  await success(runner, ["git", "push", "-u", "origin", state.branch!], "PUSH_FAILED");
  const bodyPath = resolve(root, `.autopilot/runs/${state.runId}/pr-body.md`);
  await mkdir(dirname(bodyPath), { recursive: true });
  const body = `## Summary\n\nImplements ${state.milestone!.id} — ${state.milestone!.title}.\n\n## Verification\n\n${state.verification.map((value) => `- ${value.status}: \`${value.command.join(" ")}\``).join("\n")}\n\n## Automation\n\nGenerated by repository Autopilot. Merge remains gated on exact-commit CI and independent review.\n`;
  await writeFile(bodyPath, body, { mode: 0o600 });
  const url = await success(
    runner,
    [
      "gh",
      "pr",
      "create",
      "--base",
      "main",
      "--head",
      state.branch!,
      "--title",
      `feat: ${state.milestone!.title.toLowerCase()}`,
      "--body-file",
      bodyPath,
    ],
    "PR_CREATE_FAILED",
  );
  state.prUrl = url.split("\n").at(-1) ?? null;
  const number = state.prUrl?.match(/\/(\d+)$/)?.[1];
  if (!number) throw new AutopilotError("GitHub returned an invalid PR URL", "PR_OUTPUT_INVALID");
  state.prNumber = Number(number);
  state.phase = "CI_PENDING";
  state.ciStatus = "PENDING";
  await store.save(state);
  try {
    await monitorCi(
      runner,
      state.prNumber,
      config.ciTimeoutSeconds,
      state.commit!,
      config.requiredCiChecks,
    );
    state.ciStatus = "PASSED";
  } catch (error) {
    state.ciStatus = "FAILED";
    state.phase = "FAILED";
    state.failure = error instanceof Error ? error.message : String(error);
    await store.save(state);
    throw error;
  }
  return await requestIndependentReview(root, config, runner, state);
}

async function cleanReviewWorktree(root: string, path: string, runner: CommandRunner) {
  const removed = await runner.run(["git", "worktree", "remove", "--force", path], { cwd: root });
  if (removed.exitCode !== 0) await rm(path, { recursive: true, force: true });
  await runner.run(["git", "worktree", "prune"], { cwd: root });
}

async function runReviewAtCommit(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
  commit: string,
  promptPath: string,
) {
  const worktree = resolve(
    root,
    ".autopilot",
    "review-worktrees",
    state.runId,
    commit.slice(0, 12),
  );
  await cleanReviewWorktree(root, worktree, runner);
  await mkdir(dirname(worktree), { recursive: true });
  await success(
    runner,
    ["git", "worktree", "add", "--detach", worktree, commit],
    "REVIEW_WORKTREE_FAILED",
    { cwd: root },
  );
  try {
    return await runner.run(
      [...config.reviewAgentCommand!, promptPath],
      agentOptions(root, state, config, `review-${commit.slice(0, 12)}`, worktree),
    );
  } finally {
    await cleanReviewWorktree(root, worktree, runner);
  }
}

export async function requestIndependentReview(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
): Promise<RunState> {
  await assertRecordedBranch(runner, state);
  if (!state.prNumber || !state.milestone)
    throw new AutopilotError("No PR is ready for review", "REVIEW_NOT_READY");
  if (state.ciStatus !== "PASSED" || !state.commit)
    throw new AutopilotError(
      "Exact-head CI must pass before independent review",
      "REVIEW_NOT_READY",
    );
  const expectedCommit = await prHeadCommit(runner, state.prNumber);
  if (expectedCommit !== state.commit)
    throw new AutopilotError("PR head changed after CI passed", "CI_STALE");
  const promptPath = resolve(
    root,
    `.autopilot/runs/${state.runId}/review-${expectedCommit.slice(0, 12)}.txt`,
  );
  await mkdir(dirname(promptPath), { recursive: true });
  await writeFile(promptPath, reviewPrompt(state.prNumber, state.milestone, expectedCommit), {
    mode: 0o600,
  });
  state.phase = "AWAITING_REVIEW";
  state.reviewedCommit = null;
  state.reviewVerdict = "NOT_RUN";
  state.failure = null;
  const store = new StateStore(root);
  await store.save(state);
  if (!config.reviewAgentCommand) return state;
  let parsed: ReviewResult;
  try {
    const result = await runReviewAtCommit(root, config, runner, state, expectedCommit, promptPath);
    if (result.exitCode !== 0)
      throw new AutopilotError(result.stderr || "Independent review failed", "REVIEW_FAILED");
    parsed = parseReviewResult(result.stdout);
  } catch (error) {
    state.phase = "AWAITING_REVIEW";
    state.failure = error instanceof Error ? error.message : String(error);
    await store.save(state);
    throw error;
  }
  return await applyParsedReviewResult(root, config, runner, state, parsed, expectedCommit);
}

export async function applyReviewResult(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
  raw: string,
) {
  const expectedCommit = await prHeadCommit(runner, state.prNumber!);
  return await applyParsedReviewResult(
    root,
    config,
    runner,
    state,
    parseReviewResult(raw),
    expectedCommit,
  );
}

async function applyParsedReviewResult(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
  result: ReviewResult,
  expectedCommit: string,
): Promise<RunState> {
  await assertRecordedBranch(runner, state);
  const currentCommit = await prHeadCommit(runner, state.prNumber!);
  if (
    result.reviewedCommit !== expectedCommit ||
    currentCommit !== expectedCommit ||
    state.commit !== expectedCommit ||
    state.ciStatus !== "PASSED"
  )
    throw new AutopilotError(
      "PR head changed or review did not match its exact commit",
      "REVIEW_STALE",
    );
  state.reviewedCommit = expectedCommit;
  state.reviewVerdict = result.verdict;
  state.findings = result.findings;
  state.failure = null;
  const store = new StateStore(root);
  const objective = unresolvedObjectiveFindings(state.findings);
  if (objective.length) {
    if (!config.implementationAgentCommand) {
      state.phase = "REMEDIATING";
      await store.save(state);
      return state;
    }
    if (state.remediationAttempts >= config.remediationLoopLimit) {
      state.phase = "FAILED";
      state.failure = "Remediation loop limit reached";
      await store.save(state);
      return state;
    }
    state.remediationAttempts += 1;
    state.phase = "REMEDIATING";
    await store.save(state);
    try {
      const promptPath = resolve(
        root,
        `.autopilot/runs/${state.runId}/remediation-${state.remediationAttempts}.txt`,
      );
      await mkdir(dirname(promptPath), { recursive: true });
      await writeFile(promptPath, remediationPrompt(state.milestone!, objective, config), {
        mode: 0o600,
      });
      const fixed = await runner.run(
        [...config.implementationAgentCommand, promptPath],
        agentOptions(root, state, config, `remediation-${state.remediationAttempts}`),
      );
      if (fixed.exitCode !== 0)
        throw new AutopilotError(fixed.stderr || "Remediation agent failed", "REMEDIATION_FAILED");
      state.verification = await verify(root, config, runner, state.runId);
      if (state.verification.some((value) => value.status === "FAILED")) {
        state.phase = "FAILED";
        state.failure = "Remediation verification failed";
        await store.save(state);
        return state;
      }
      await enforceChangeSafety(root, config, runner, state);
      await success(runner, ["git", "add", "-A"], "STAGE_FAILED");
      await success(
        runner,
        ["git", "commit", "-m", "fix: address independent review findings"],
        "COMMIT_FAILED",
      );
      state.commit = await success(runner, ["git", "rev-parse", "HEAD"], "COMMIT_READ_FAILED");
      await success(runner, ["git", "push"], "PUSH_FAILED");
      state.reviewedCommit = null;
      state.reviewVerdict = "NOT_RUN";
      state.ciStatus = "PENDING";
      state.phase = "CI_PENDING";
      await store.save(state);
      await monitorCi(
        runner,
        state.prNumber!,
        config.ciTimeoutSeconds,
        state.commit!,
        config.requiredCiChecks,
      );
      state.ciStatus = "PASSED";
      state.phase = "AWAITING_REVIEW";
      await store.save(state);
    } catch (error) {
      state.phase = "FAILED";
      state.failure = error instanceof Error ? error.message : String(error);
      await store.save(state);
      throw error;
    }
    return await requestIndependentReview(root, config, runner, state);
  }
  state.phase = "READY_TO_MERGE";
  await store.save(state);
  if (config.autoMerge) return await mergeReady(root, config, runner, state);
  return state;
}

export async function mergeReady(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
  options: { manual?: boolean } = {},
) {
  await assertRecordedBranch(runner, state);
  const infoRaw = await success(
    runner,
    ["gh", "pr", "view", String(state.prNumber), "--json", "mergeable,state"],
    "PR_READ_FAILED",
  );
  const info = JSON.parse(infoRaw) as { mergeable: string; state: string };
  if (info.state !== "OPEN")
    throw new AutopilotError(`PR is ${info.state.toLowerCase()}, not open`, "MERGE_BLOCKED");
  const currentHead = await prHeadCommit(runner, state.prNumber!);
  if (
    !state.reviewedCommit ||
    currentHead !== state.reviewedCommit ||
    state.commit !== state.reviewedCommit
  )
    throw new AutopilotError("PR head changed after independent review", "REVIEW_STALE");
  const blocked = mergeGate(state, info.mergeable === "MERGEABLE");
  if (blocked.length)
    throw new AutopilotError(`Merge blocked: ${blocked.join("; ")}`, "MERGE_BLOCKED");
  if (!config.autoMerge && !options.manual)
    throw new AutopilotError("Auto-merge is disabled in configuration", "MERGE_APPROVAL_REQUIRED");
  await success(
    runner,
    [
      "gh",
      "pr",
      "merge",
      String(state.prNumber),
      "--merge",
      "--match-head-commit",
      state.reviewedCommit,
    ],
    "MERGE_FAILED",
  );
  await success(runner, ["git", "checkout", "main"], "CHECKOUT_MAIN_FAILED");
  await success(runner, ["git", "pull", "--ff-only", "origin", "main"], "SYNC_FAILED");
  await runner.run(["git", "branch", "-d", state.branch!]);
  const clean = await success(runner, ["git", "status", "--porcelain"], "GIT_STATUS_FAILED");
  if (clean) throw new AutopilotError("Repository is not clean after merge", "POST_MERGE_DIRTY");
  state.phase = "COMPLETE";
  state.failure = null;
  state.completedAt = new Date().toISOString();
  await new StateStore(root).save(state);
  return state;
}

export async function reviewResultFromFile(path: string) {
  return await readFile(path, "utf8");
}

const findingSchema = z
  .object({
    severity: z.enum(["BLOCKING", "IMPORTANT", "OPTIONAL"]),
    summary: z.string().trim().min(1),
    file: z.string().trim().min(1).nullable(),
    line: z.number().int().positive().nullable(),
  })
  .strict();
const reviewSchema = z
  .object({
    reviewedCommit: z.string().regex(/^[0-9a-f]{40}$/),
    verdict: z.enum(["APPROVED", "CHANGES_REQUIRED"]),
    findings: z.array(findingSchema),
  })
  .strict()
  .superRefine((result, context) => {
    const objective = result.findings.some(
      (finding) => finding.severity === "BLOCKING" || finding.severity === "IMPORTANT",
    );
    if ((result.verdict === "APPROVED") === objective) {
      context.addIssue({
        code: "custom",
        message: "Verdict must match the presence of objective findings",
      });
    }
  });

export function parseReviewResult(raw: string): ReviewResult {
  try {
    return reviewSchema.parse(JSON.parse(raw));
  } catch {
    throw new AutopilotError(
      "Review result must be valid, internally consistent structured JSON",
      "REVIEW_OUTPUT_INVALID",
    );
  }
}

async function prHeadCommit(runner: CommandRunner, pr: number) {
  const raw = await success(
    runner,
    ["gh", "pr", "view", String(pr), "--json", "headRefOid"],
    "PR_READ_FAILED",
  );
  const parsed = JSON.parse(raw) as { headRefOid?: string };
  if (!parsed.headRefOid)
    throw new AutopilotError("PR head commit was missing", "PR_OUTPUT_INVALID");
  return parsed.headRefOid;
}
