import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import type { CommandRunner, Config, Finding, RunState } from "./types";
import { AutopilotError } from "./errors";
import { StateStore } from "./state-store";
import { verify } from "./verification";
import { monitorCi } from "./github";
import { mergeGate } from "./policy";
import { reviewPrompt, unresolvedObjectiveFindings } from "./prompts";
import { z } from "zod";

async function success(runner: CommandRunner, command: string[], code: string) {
  const result = await runner.run(command);
  if (result.exitCode !== 0)
    throw new AutopilotError(result.stderr || `${command[0]} failed`, code);
  return result.stdout.trim();
}

function changedPaths(status: string) {
  return status
    .split("\n")
    .filter(Boolean)
    .map((line) => ({ code: line.slice(0, 2), path: line.slice(3).split(" -> ").at(-1)! }));
}

export async function assertRecordedBranch(runner: CommandRunner, state: RunState) {
  if (state.dryRun)
    throw new AutopilotError("Dry-run state cannot mutate the repository", "DRY_RUN_MUTATION");
  const current = await success(runner, ["git", "branch", "--show-current"], "GIT_BRANCH_FAILED");
  if (!state.branch || current !== state.branch)
    throw new AutopilotError(
      `Recorded branch ${state.branch ?? "<none>"} is not checked out`,
      "BRANCH_MISMATCH",
    );
}

export async function enforceChangeSafety(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
) {
  const statusResult = await runner.run(["git", "status", "--porcelain", "--untracked-files=all"]);
  if (statusResult.exitCode !== 0)
    throw new AutopilotError(statusResult.stderr || "git status failed", "DIFF_READ_FAILED");
  const status = statusResult.stdout;
  const changed = changedPaths(status);
  const protectedChange = changed.find(({ path }) =>
    config.protectedPaths.some(
      (protectedPath) => path === protectedPath || path.startsWith(`${protectedPath}/`),
    ),
  );
  if (protectedChange) {
    state.approvalGates.push(`protected path changed: ${protectedChange.path}`);
    throw new AutopilotError(`Protected path changed: ${protectedChange.path}`, "PROTECTED_PATH");
  }
  const migrations = changed.filter(({ path }) =>
    /^prisma\/migrations\/.+\/migration\.sql$/.test(path),
  );
  let destructive = migrations.some(({ code }) => code.includes("D"));
  for (const migration of migrations) {
    if (migration.code.includes("D")) continue;
    try {
      const sql = await readFile(resolve(root, migration.path), "utf8");
      if (/\b(DROP\s+(TABLE|COLUMN|TYPE)|TRUNCATE|DELETE\s+FROM)\b/i.test(sql)) destructive = true;
    } catch {
      destructive = true;
    }
  }
  if (destructive) {
    state.approvalGates.push("destructive schema migration requires human approval");
    throw new AutopilotError("Destructive migration detected", "APPROVAL_REQUIRED");
  }
}

export async function advanceImplemented(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
) {
  const store = new StateStore(root);
  await assertRecordedBranch(runner, state);
  state.phase = "VERIFYING";
  await store.save(state);
  state.verification = await verify(root, config, runner, state.runId);
  if (state.verification.some((value) => value.status === "FAILED")) {
    state.phase = "FAILED";
    state.failure = "Local verification failed";
    await store.save(state);
    return state;
  }
  state.phase = "VERIFIED";
  await store.save(state);
  await enforceChangeSafety(root, config, runner, state);
  await success(runner, ["git", "add", "-A"], "STAGE_FAILED");
  await success(
    runner,
    ["git", "commit", "-m", `feat: ${state.milestone!.title.toLowerCase()}`],
    "COMMIT_FAILED",
  );
  state.commit = await success(runner, ["git", "rev-parse", "HEAD"], "COMMIT_READ_FAILED");
  await success(runner, ["git", "push", "-u", "origin", state.branch!], "PUSH_FAILED");
  const bodyPath = resolve(root, `.autopilot/runs/${state.runId}/pr-body.md`);
  await mkdir(dirname(bodyPath), { recursive: true });
  const body = `## Summary\n\nImplements ${state.milestone!.id} — ${state.milestone!.title}.\n\n## Verification\n\n${state.verification.map((value) => `- ${value.status}: \`${value.command.join(" ")}\``).join("\n")}\n\n## Automation\n\nGenerated by repository Autopilot. Merge remains gated on CI and independent review.\n`;
  await writeFile(bodyPath, body, { mode: 0o600 });
  const url = await success(
    runner,
    [
      "gh",
      "pr",
      "create",
      "--base",
      "main",
      "--head",
      state.branch!,
      "--title",
      `feat: ${state.milestone!.title.toLowerCase()}`,
      "--body-file",
      bodyPath,
    ],
    "PR_CREATE_FAILED",
  );
  state.prUrl = url.split("\n").at(-1) ?? null;
  const number = state.prUrl?.match(/\/(\d+)$/)?.[1];
  if (!number) throw new AutopilotError("GitHub returned an invalid PR URL", "PR_OUTPUT_INVALID");
  state.prNumber = Number(number);
  state.phase = "CI_PENDING";
  state.ciStatus = "PENDING";
  await store.save(state);
  try {
    await monitorCi(runner, state.prNumber, config.ciTimeoutSeconds);
    state.ciStatus = "PASSED";
  } catch (error) {
    state.ciStatus = "FAILED";
    state.phase = "FAILED";
    state.failure = error instanceof Error ? error.message : String(error);
    await store.save(state);
    throw error;
  }
  const promptPath = resolve(root, `.autopilot/runs/${state.runId}/review-prompt.txt`);
  await writeFile(promptPath, reviewPrompt(state.prNumber, state.milestone!), { mode: 0o600 });
  state.phase = "AWAITING_REVIEW";
  await store.save(state);
  if (config.reviewAgentCommand) {
    const result = await runner.run([...config.reviewAgentCommand, promptPath]);
    if (result.exitCode !== 0) throw new AutopilotError(result.stderr, "REVIEW_FAILED");
    await applyReviewResult(root, config, runner, state, result.stdout);
  }
  return state;
}

export async function applyReviewResult(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
  raw: string,
) {
  const result = parseReviewResult(raw);
  await assertRecordedBranch(runner, state);
  state.reviewedCommit = await prHeadCommit(runner, state.prNumber!);
  state.reviewVerdict = result.verdict;
  state.findings = result.findings;
  const store = new StateStore(root);
  const objective = unresolvedObjectiveFindings(state.findings);
  if (objective.length) {
    if (!config.implementationAgentCommand) {
      state.phase = "REMEDIATING";
      await store.save(state);
      return state;
    }
    if (state.remediationAttempts >= config.remediationLoopLimit) {
      state.phase = "FAILED";
      state.failure = "Remediation loop limit reached";
      await store.save(state);
      return state;
    }
    state.remediationAttempts += 1;
    state.phase = "REMEDIATING";
    await store.save(state);
    const path = resolve(
      root,
      `.autopilot/runs/${state.runId}/remediation-${state.remediationAttempts}.json`,
    );
    await writeFile(path, JSON.stringify(objective, null, 2), { mode: 0o600 });
    const fixed = await runner.run([...config.implementationAgentCommand, path]);
    if (fixed.exitCode !== 0) throw new AutopilotError(fixed.stderr, "REMEDIATION_FAILED");
    state.verification = await verify(root, config, runner, state.runId);
    if (state.verification.some((value) => value.status === "FAILED"))
      throw new AutopilotError("Remediation verification failed", "VERIFY_FAILED");
    await enforceChangeSafety(root, config, runner, state);
    await success(runner, ["git", "add", "-A"], "STAGE_FAILED");
    await success(
      runner,
      ["git", "commit", "-m", "fix: address independent review findings"],
      "COMMIT_FAILED",
    );
    await success(runner, ["git", "push"], "PUSH_FAILED");
    state.ciStatus = "PENDING";
    await store.save(state);
    await monitorCi(runner, state.prNumber!, config.ciTimeoutSeconds);
    state.ciStatus = "PASSED";
    state.phase = "AWAITING_REVIEW";
    await store.save(state);
    return state;
  }
  state.phase = "READY_TO_MERGE";
  await store.save(state);
  return state;
}

export async function mergeReady(
  root: string,
  config: Config,
  runner: CommandRunner,
  state: RunState,
) {
  await assertRecordedBranch(runner, state);
  const infoRaw = await success(
    runner,
    ["gh", "pr", "view", String(state.prNumber), "--json", "mergeable,state"],
    "PR_READ_FAILED",
  );
  const info = JSON.parse(infoRaw) as { mergeable: string; state: string };
  const currentHead = await prHeadCommit(runner, state.prNumber!);
  if (!state.reviewedCommit || currentHead !== state.reviewedCommit)
    throw new AutopilotError("PR head changed after independent review", "REVIEW_STALE");
  const blocked = mergeGate(state, info.mergeable === "MERGEABLE");
  if (blocked.length)
    throw new AutopilotError(`Merge blocked: ${blocked.join("; ")}`, "MERGE_BLOCKED");
  if (!config.autoMerge)
    throw new AutopilotError("Auto-merge is disabled in configuration", "MERGE_APPROVAL_REQUIRED");
  await success(
    runner,
    [
      "gh",
      "pr",
      "merge",
      String(state.prNumber),
      "--merge",
      "--delete-branch",
      "--match-head-commit",
      state.reviewedCommit,
    ],
    "MERGE_FAILED",
  );
  await success(runner, ["git", "checkout", "main"], "CHECKOUT_MAIN_FAILED");
  await success(runner, ["git", "pull", "--ff-only", "origin", "main"], "SYNC_FAILED");
  await runner.run(["git", "branch", "-d", state.branch!]);
  const clean = await success(runner, ["git", "status", "--porcelain"], "GIT_STATUS_FAILED");
  if (clean) throw new AutopilotError("Repository is not clean after merge", "POST_MERGE_DIRTY");
  state.phase = "COMPLETE";
  state.completedAt = new Date().toISOString();
  await new StateStore(root).save(state);
  return state;
}

export async function reviewResultFromFile(path: string) {
  return await readFile(path, "utf8");
}

const findingSchema = z
  .object({
    severity: z.enum(["BLOCKING", "IMPORTANT", "OPTIONAL"]),
    summary: z.string().trim().min(1),
    resolved: z.boolean(),
  })
  .strict();
const reviewSchema = z
  .object({
    verdict: z.enum(["APPROVED", "CHANGES_REQUIRED"]),
    findings: z.array(findingSchema),
  })
  .strict();

export function parseReviewResult(raw: string): {
  verdict: "APPROVED" | "CHANGES_REQUIRED";
  findings: Finding[];
} {
  try {
    return reviewSchema.parse(JSON.parse(raw));
  } catch {
    throw new AutopilotError(
      "Review result must be valid structured JSON",
      "REVIEW_OUTPUT_INVALID",
    );
  }
}

async function prHeadCommit(runner: CommandRunner, pr: number) {
  const raw = await success(
    runner,
    ["gh", "pr", "view", String(pr), "--json", "headRefOid"],
    "PR_READ_FAILED",
  );
  const parsed = JSON.parse(raw) as { headRefOid?: string };
  if (!parsed.headRefOid)
    throw new AutopilotError("PR head commit was missing", "PR_OUTPUT_INVALID");
  return parsed.headRefOid;
}
