import { type Brand, defineId } from "../shared";

/**
 * Identity of an internal Stroman OS user. This is the STABLE business identity:
 * it is generated by Stroman OS, not by the authentication provider, so it
 * survives a provider migration. The provider's subject is mapped to it via
 * `UserIdentity` and never used directly as a business identifier.
 *
 * The `usr_` prefix is shared with `OwnerId` on purpose: in the MVP ownership
 * model the internal user id *is* the owner id (owner mapping Option A). The
 * mapping is made explicit at the application boundary, not by treating the two
 * brands as interchangeable.
 */
export type UserId = Brand<string, "UserId">;
export const UserId = defineId<"UserId">("UserId", "usr");

/** Lifecycle state of an internal user. Disabled users cannot access resources. */
export type AccountStatus = "ACTIVE" | "DISABLED";
export const ACCOUNT_STATUSES: readonly AccountStatus[] = ["ACTIVE", "DISABLED"];
